# Header
menu:
  Home: /
  Archives: /archives
  About: /about
banner: banner.jpg
subtitle: You'll never walk alone

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5
# Footer
copyright: |-
  <a href="https://beian.miit.gov.cn/" target="_blank">ICP备案号：沪ICP备17007510号</a>
  <a href="https://beian.miit.gov.cn/" target="_blank">ICP备案号：沪ICP备17007510号-1</a>
# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:

# Header links
# Each name must correspond to the icon name of Fork Awesome
# https://forkaweso.me/Fork-Awesome/icons/
#links:
#  github: https://github.com/your_github_account
#  twitter: https://twitter.com/your_twitter_account
#  telegram: https://t.me/your_telegram_account